/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TicketsService } from "../tickets.service";
import { TicketsCreateInput } from "./TicketsCreateInput";
import { Tickets } from "./Tickets";
import { TicketsFindManyArgs } from "./TicketsFindManyArgs";
import { TicketsWhereUniqueInput } from "./TicketsWhereUniqueInput";
import { TicketsUpdateInput } from "./TicketsUpdateInput";

export class TicketsControllerBase {
  constructor(protected readonly service: TicketsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Tickets })
  async createTickets(
    @common.Body() data: TicketsCreateInput
  ): Promise<Tickets> {
    return await this.service.createTickets({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Tickets] })
  @ApiNestedQuery(TicketsFindManyArgs)
  async ticketsItems(@common.Req() request: Request): Promise<Tickets[]> {
    const args = plainToClass(TicketsFindManyArgs, request.query);
    return this.service.ticketsItems({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        subject: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Tickets })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async tickets(
    @common.Param() params: TicketsWhereUniqueInput
  ): Promise<Tickets | null> {
    const result = await this.service.tickets({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        subject: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Tickets })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTickets(
    @common.Param() params: TicketsWhereUniqueInput,
    @common.Body() data: TicketsUpdateInput
  ): Promise<Tickets | null> {
    try {
      return await this.service.updateTickets({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          status: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Tickets })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTickets(
    @common.Param() params: TicketsWhereUniqueInput
  ): Promise<Tickets | null> {
    try {
      return await this.service.deleteTickets({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          status: true,
          subject: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
